clone:
  git:
    image: plugins/git
    skip_verify: true


pipeline:
  build:
    image: node:alpine
    commands:
      - rm package-lock.json
      - npm install --registry https://registry.plt.et.tu-dresden.de:4873 pfe-ree-interface
      - npm install
      - npm run-script apidoc build
      - npm test

  gitea_release:
    image: plugins/gitea-release
    api_key: 457b766b1fddc3832abc1ab47f39c74efa951f50
    base_url: https://dev.plt.et.tu-dresden.de
    files:
      - build/*
      - apidoc/*
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    when:
      event: [ tag ]

  docker:
    image: plugins/docker
    auto_tag: true
    repo: registry.plt.et.tu-dresden.de/pfe-ree-node
    registry: registry.plt.et.tu-dresden.de

  notify:
    image: drillster/drone-email
    host: mail.zih.tu-dresden.de
    username: plt
    password: $EMAIL_PASSWORD
    secrets: [ email_password ]
    from: plt@mailbox.tu-dresden.de
    recipients: [ markus.graube@tu-dresden.de ]
    when:
      status: [ changed, failure ]

