---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:

- name: build
  image: node:8-jessie
  commands:
  - npm install
  - npm run-script apidoc build

- name: test
  image: node:8-jessie
  commands:
  - export LOGLEVEL=warn
  - npm test

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: p2olab/polaris-backend
    auto_tag: true

- name: docker-arm
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: p2olab/polaris-backend
    auto_tag: true
    auto_tag_suffix: arm

- name: notify
  image: drillster/drone-email
  settings:
    from: "plt@mailbox.tu-dresden.de"
    host: mail.zih.tu-dresden.de
    password:
      from_secret: email_password
    username: plt
  when:
    status:
    - changed
    - failure

---
kind: signature
hmac: 3da37f340aa0a034ade22786242f59202c1298cbfb06fdb59988f9d090a7f0a2

...
