clone:
  git:
    image: plugins/git
    skip_verify: true


pipeline:

  build:
    image: node:8-jessie
    commands:
      - npm config set @plt:registry https://registry.plt.et.tu-dresden.de:4873 
      - npm install
      - npm run-script apidoc build

  test:
    image: node:8-jessie
    commands:
      - npm test

  docker-develop:
    image: docker
    privileged: true
    commands:
      - docker build -t registry.plt.et.tu-dresden.de/pfe-ree-node:develop .
      - docker build -f Dockerfile.arm -t registry.plt.et.tu-dresden.de/pfe-ree-node:develop-arm .
      - docker push registry.plt.et.tu-dresden.de/pfe-ree-node:develop
      - docker push registry.plt.et.tu-dresden.de/pfe-ree-node:develop-arm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch:
        - develop

  docker-stable:
    image: docker
    privileged: true
    commands:
      - docker build -t registry.plt.et.tu-dresden.de/pfe-ree-node:stable .
      - docker build -f Dockerfile.arm -t registry.plt.et.tu-dresden.de/pfe-ree-node:stable-arm .
      - docker push registry.plt.et.tu-dresden.de/pfe-ree-node:stable
      - docker push registry.plt.et.tu-dresden.de/pfe-ree-node:stable-arm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch:
        - stable

  docker-tag:
    image: docker
    privileged: true
    commands:
      - docker build -t "registry.plt.et.tu-dresden.de/pfe-ree-node:${DRONE_TAG##v}" .
      - docker build -f Dockerfile.arm -t "registry.plt.et.tu-dresden.de/pfe-ree-node:${DRONE_TAG##v}-arm" .
      - docker push "registry.plt.et.tu-dresden.de/pfe-ree-node:${DRONE_TAG##v}"
      - docker push "registry.plt.et.tu-dresden.de/pfe-ree-node:${DRONE_TAG##v}-arm"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
       event:
       - tag

  notify:
    image: drillster/drone-email
    host: mail.zih.tu-dresden.de
    username: plt
    password: $EMAIL_PASSWORD
    secrets: [ email_password ]
    from: plt@mailbox.tu-dresden.de
    recipients: [ markus.graube@tu-dresden.de ]
    when:
      status: [ changed, failure ]
