clone:
  git:
    image: plugins/git
    skip_verify: true


pipeline:

  docker:
    image: plugins/docker
    settings:
      debug: true
      custom_dns:
        - 10.4.50.6
      repo: registry.plt.et.tu-dresden.de/pfe-ree-node
      registry: registry.plt.et.tu-dresden.de
      auto_tag: true

  build:
    image: node:8-jessie
    commands:
      - npm config set @plt:registry https://registry.plt.et.tu-dresden.de:4873 
      - npm install
      - npm run-script apidoc build

  test:
    image: node:8-jessie
    commands:
      - npm test



  docker-pi:
    image: plugins/docker
    settings:
      debug: true
      dockerfile: Dockerfile.arm
      repo: registry.plt.et.tu-dresden.de/pfe-ree-node
      registry: registry.plt.et.tu-dresden.de
      auto_tag: true
      auto_tag_suffix: arm

  notify:
    image: drillster/drone-email
    host: mail.zih.tu-dresden.de
    username: plt
    password: $EMAIL_PASSWORD
    secrets: [ email_password ]
    from: plt@mailbox.tu-dresden.de
    recipients: [ markus.graube@tu-dresden.de ]
    when:
      status: [ changed, failure ]

