clone:
  git:
    image: plugins/git
    skip_verify: true


pipeline:
  build:
    image: node:latest
    commands:
      - npm install
      - npm run-script apidoc build
      - npm run test

  docker:
    image: plugins/docker
    repo: registry.plt.et.tu-dresden.de/pfe-ree-node
    registry: registry.plt.et.tu-dresden.de

  docker-arm:
      image: plugins/docker
      repo: registry.plt.et.tu-dresden.de/pfe-ree-node/arm
      registry: registry.plt.et.tu-dresden.de
      dockerfile: Dockerfile.arm

  notify:
    image: drillster/drone-email
    host: mail.zih.tu-dresden.de
    username: plt
    password: $EMAIL_PASSWORD
    secrets: [ email_password ]
    from: plt@mailbox.tu-dresden.de
    recipients: [ markus.graube@tu-dresden.de ]
    when:
      status: [ changed, failure ]
