clone:
  git:
    image: plugins/git
    skip_verify: true


pipeline:
  docker:
    image: docker
    privileged: true
    commands:
      - docker build -t registry.plt.et.tu-dresden.de/pfe-ree-node -t registry.plt.et.tu-dresden.de/pfe-ree-node:$DRONE_BRANCH .
      - docker build -f Dockerfile.arm -t registry.plt.et.tu-dresden.de/pfe-ree-node:latest-arm .
      - docker push registry.plt.et.tu-dresden.de/pfe-ree-node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch:
        - develop
        - feature/docker-in-docker

  build:
    image: node:8-jessie
    commands:
      - npm config set @plt:registry https://registry.plt.et.tu-dresden.de:4873 
      - npm install
      - npm run-script apidoc build

  test:
    image: node:8-jessie
    commands:
      - npm test



  notify:
    image: drillster/drone-email
    host: mail.zih.tu-dresden.de
    username: plt
    password: $EMAIL_PASSWORD
    secrets: [ email_password ]
    from: plt@mailbox.tu-dresden.de
    recipients: [ markus.graube@tu-dresden.de ]
    when:
      status: [ changed, failure ]

